baseURL: https://syntopicalreckoning.netlify.app
languageCode: en
DefaultContentLanguage: en
title: Website of Rikard Wahlström
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Rikard Wahlström
  customCss: []
  customJs: []
  description: Syntopical Reckoning
  doNotLoadAnimations: no
  favicon: favicons/
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: yes
    use: katex
  profilePicture: images/favicon.ico
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/riwahl
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:rikard.wahlstroem@gmail.com
  title: Syntopical Reckoning
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 300
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 400