---
title: Welcome to Syntopical Reckoning!
author: Rikard Wahlström
date: '2021-04-05'
slug: []
categories: []
tags: []
Description: ''
Tags: []
Categories: []
DisableComments: no
---

Hello and welcome to my newly started blog -- Syntopical Reckoning

```{r}
library(tidyverse)

ggplot(mpg) +
 aes(x = displ, y = hwy, colour = class) +
 geom_point(size = 1L) +
 scale_color_hue() +
 theme_minimal()
```

```{r betaDist, cache=TRUE, echo = FALSE, fig.cap='Density of the beta distribution', out.width='80%', fig.asp=.75, fig.align='center'}
library(ggplot2)
library(latex2exp)
cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
ggplot(data.frame(x = c(0, 1)), aes(x = x)) +
  stat_function(aes(color = "1"), fun = function(x){dbeta(x,0.5,0.5)}, size = 1.5) +
  stat_function(aes(color = "2"), fun = function(x){dbeta(x,1,1)}, size = 1.5) +
  stat_function(aes(color = "3"), fun = function(x){dbeta(x,2,2)}, size = 1.5) +
  stat_function(aes(color = "4"), fun = function(x){dbeta(x,3,2)}, size = 1.5) +
  theme_minimal() +
  xlab("x") + 
  ylab("density") +
  scale_colour_manual(values=cbp1, labels = unname(TeX(c("$\\alpha = 0.5,$ $\\beta = 0.5$",
                                                         "$\\alpha = 1.0,$ $\\beta = 1.0$",
                                                         "$\\alpha = 2.0,$ $\\beta = 2.0$",
                                                         "$\\alpha = 3.0,$ $\\beta = 2.0$"))))
```